name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Tauri App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
     - name: Install Nodejs    
        uses: pnpm/action-setup@v2
        with:
          version: ^7.25.0
     - name: Get Dependencies
        run: pnpm tauri  Install
      - name: Build
        run: pnpm tauri build