name: build and public

on:
  push:
    branches:
      - main

jobs:
   publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: |
        curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
        export PATH="$HOME/.pnpm/bin:$PATH"

    - name: Install dependencies
      run: pnpm install

    - name: Build and package app
      run: pnpm tauri build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Tauri app
        path: dist